# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-08 06:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='people',
            name='pwd',
            field=models.CharField(default='yuan123', max_length=32),
        ),
        migrations.AddField(
            model_name='people',
            name='user',
            field=models.CharField(default='yuan', max_length=16),
        ),
        migrations.AlterUniqueTogether(
            name='date2timer',
            unique_together=set([('timer', 'date', 'confe')]),
        ),
    ]
